### ISSUE TITLE
What's the license of this project?

### ISSUE THREAD

**Issue by hiiwave** [ChenCyl/vue-network-d3#1]
Hi, I'm trying to visualize some graphs, and this project looks as a very good start point. As I didn't see a LICENSE of this project, is it intended as [No License](https://choosealicense.com/no-permission/) or just you forgot adding it? Thanks.

**Comment by yulei-chen** [comment]
Hi, thanks for reminding me. I know less about license. I look up some information and decide to add a MIT License for this project. Thank you 😃
